# Generated by Django 2.2.7 on 2020-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordeddata',
            name='timestamp',
            field=models.DurationField(),
        ),
    ]
